### PR TITLE
Support docke

### PR DESCRIPTION
**Pull request by heiye1024**
Support docke

### CODE REVIEW

**Comment by heiye1024** [comment]
Added docker-compose for cross-platform development: `docker-compose up --build`

**Comment by heiye1024** [comment]
Added docker-compose for cross-platform development: docker-compose up --build

**Comment by DaanSelen** [comment]
I think this is already solved with the new alpine Docker container?

**Comment by DaanSelen** [comment]
@heiye1024 are you still developing this?

**Comment by DaanSelen** [comment]
Closing due to inactivity

**Pull request closed without merging**
