### PR TITLE
Big Docker Image update.

### PR DESCRIPTION
**Pull request by DaanSelen**
Hi Donald, after working hard on this Docker image update:

Fixed Docker Readme for: https://github.com/donaldzou/WGDashboard/pull/430

Added new persistency through symlinks, which makes the biggest feature possible \/
Added Docker image update possibility. From for example 4.0.3 -> 4.0.4 (as long as Arch Linux is supported in `wgd.sh`.

Refactored lots of code.

### CODE REVIEW

**Comment by donaldzou** [comment]
Thank u for working on this! Just wondering, is ArchLinux the best option for the Docker base OS? Curious why not Ubuntu?

**Comment by DaanSelen** [comment]
Hi Donald, It's not Arch but Alpine. Ubuntu would also be possible but it comes packaged with more... everything, so it creates a bigger image,

**Comment by donaldzou** [comment]
> Hi Donald, It's not Arch but Alpine. Ubuntu would also be possible but it comes packaged with more... everything, so it creates a bigger image,

Ahh gotcha, I guess Alpine is better then :)

**Comment by DaanSelen** [comment]
Saying better is always opinionated, but it is a general choice of many... many docker images! We could perhaps in the future look into the python image based on alpine as a base. But the image itself is already (compressed) 33.48 MB, which is... in my opinion pretty small.

**Comment by donaldzou** [comment]
> Saying better is always opinionated, but it is a general choice of many... many docker images! We could perhaps in the future look into the python image based on alpine as a base (if there is one). But the image itself is already (compressed) 33.48 MB, which is... in my opinion pretty small.
> 
> You can test the image yourself, if you'd like! It works much better now! Or pull it from `dselen/wgdashboard:latest`

Gotcha gotcha, yeah I think a smaller image size would be better :)

**Review by donaldzou — APPROVED** [review]

**Comment by donaldzou** [comment]
Hi Daan, are you still working on this PR?

**Comment by DaanSelen** [comment]
> Hi @DaanSelen , are you still working on this PR?

For now I am done. Before I keep making changes. Next one will be the language.

**Comment by DaanSelen** [comment]
I can merge now, but before that I am going to do some more testing. So I don't break anything.

**Pull request merged**
