### PR TITLE
add spanish lang

### PR DESCRIPTION
**Pull request by TheSL18**

### CODE REVIEW

**Comment by donaldzou** [comment]
@TheSL18 Hi! I left a comment in your commit, do you mind look over it please? Thank you!

**Comment by TheSL18** [comment]
> @TheSL18 Hi! I left a comment in your commit, do you mind look over it please? Thank you!

@donaldzou Hi, I don't see the comment...

**Comment by donaldzou** [comment]
That's weird lol

image

**Comment by DaanSelen** [comment]
> That's weird lol
> 
> image

Does this also apply to the Dutch one now? I copied the German one as template.

**Comment by DaanSelen** [comment]
@TheSL18 is there something wrong? Your translations looked fine!

**Comment by TheSL18** [comment]
Yeah, I made a rookie mistake, I didn't push the changes from the main repository and I got into a conflict one when I corrected my mistake, I'm merging all the changes to upload the new result.

**Comment by TheSL18** [comment]
image
Specifically this is the error

**Comment by donaldzou** [comment]
Hi @TheSL18 , just wondering in the Spanish JSON file.. you have these lines of translation included, but they don't appear in WGDashboard:

```json
{
	"This settings will be kept inside your configuration file": "Estas configuraciones se mantendrán dentro de tu archivo de configuración",
	"Keep default / change it later": "Mantén el valor predeterminado / cámbialo más tarde",
	"Example": "Ejemplo",
	"Skip this section": "Omitir esta sección",
	"Port": "Puerto",
	"Connection Type": "Tipo de conexión",
	"Encryption": "Cifrado",
	"Strict Transport Security": "Seguridad estricta de transporte",
	"Enable": "Habilitar",
	"Disable": "Deshabilitar",
	"DNS over HTTPS": "DNS sobre HTTPS",
	"Timezone": "Zona horaria",
	"Login": "Iniciar sesión"
}
```

Just wondering where they apply to?

**Review by donaldzou — CHANGES_REQUESTED** [review]
Line 164 to line 177 is not included in WGDashboard

**Comment by DaanSelen** [comment]
I do love that commit message.

**Comment by rcv11x** [comment]
just yesterday i was going to make a new PR to add the spanish language, but i saw this user's PR. i hope it will be merged soon thanks 👍🏼

**Comment by DaanSelen** [comment]
@rcv11x @jpizquierdo if you want to overlook this and make sure you all agree? I do not speak Spanish so you all are better for that!

**Review by jpizquierdo — APPROVED** [review]
It seems good to me, go for it!

**Comment by DaanSelen** [comment]
Lang name must be english it has espanol twice

**Review by jpizquierdo — APPROVED** [review]

**Comment by DaanSelen** [comment]
I accidentally closed this branch which closed the PR. Wanting to merge it into 4.2-dev branch

**Pull request closed without merging**
