### PR TITLE
v4 Draft: Add url prefix. like http://localhost:10086/url_prefix

### PR DESCRIPTION
**Pull request by shuricksumy**
Hi @donaldzou 

I'm looking for way to configure this app with reverse proxy and use it wit some configurable url prefix like
http://localhost:10086/url_prefix

I am not good enough at VueJS but can you check this pull request and see if it is possible or acceptable for you to add such functionality

1. The python is easily configured by using
```
sudo "$venv_gunicorn" --config ./gunicorn.conf.py --env SCRIPT_NAME=${URL_PREFIX}
```
2. But front-end needs prefix like variable and not absolute path for some resources

So please look at this, and maybe it will be possible to implement this. This is a very common and useful feature that allows use application on some common host but with custom URL prefix.

PS: I tested this variant - it's works, but the code maybe done not in proper way.

### CODE REVIEW

**Comment by donaldzou** [comment]
Hi! I followed your idea made an update to v4 with adding an `app_prefix` into the `wg-dashboard.ini` without the need to change every files. Currently it can only be change manually. 

More details: https://github.com/donaldzou/WGDashboard/commit/a30843cff979fecbd6bed9d385dcc9763a2b9c78

To to add the prefix, you can simply edit the `wg-dashboard.ini`, add a new entry under the `[Server]` section 
```
[Server]
...
app_prefix = /donaldzou/1234
```
Remember to not add slash after the prefix. The app will add one automatically.

Let me know if this works :)

**Comment by donaldzou** [comment]
And it even works with cross-server

Screenshot 2024-08-14 at 1 29 51 AM

**Comment by shuricksumy** [comment]
Hi, @donaldzou 
Thanks a lot for your job, it works.

I added it inside docker, added env vars to contorl this and tested on real host.
And it perfectly works with IP bit not host name
Because of CORS

Can you suggest how this can be fixed?

image

**Comment by shuricksumy** [comment]
@donaldzou 
Thanks a lot for your job.

It works.
I am testing it now using docker and traefik rules. will let you know.

Thanks

**Comment by shuricksumy** [comment]
@donaldzou 
Can you check the protocol (http/https) in prefix URL in front-end

In case it proxy over http -> https - it requests API calls to http

`
Mixed Content: The page at 'https://myhost/wgdashboard/#/signin' was loaded over HTTPS, but requested an insecure resource 'http://myhost/wgdashboard/api/isTotpEnabled'. This request has been blocked; the content must be served over HTTPS
`

**Comment by donaldzou** [comment]
Hi @shuricksumy, just pushed a small changes on the frontend code, let me know if it works :)

**Comment by shuricksumy** [comment]
@donaldzou 
Unfortunately, this did not help((
Maybe the redirection is done by server side or some other logic.
It's still ask over http

`
Mixed Content: The page at 'https://myhost/wgdashboard/#/signin' was loaded over HTTPS, but requested an insecure resource 'http://myhost/wgdashboard/api/getDashboardTheme'. This request has been blocked; the content must be served over HTTPS.
`
`
wgdashboard/#/signin:1 Mixed Content: The page at 'https://myhost/wgdashboard/#/signin' was loaded over HTTPS, but requested an insecure resource 'http://myhost/wgdashboard/api/isTotpEnabled'. This request has been blocked; the content must be served over HTTPS.
`

**Comment by donaldzou** [comment]
Hmmmm this is weird. With `v4`, every front-end activity is done on front-end with Vue.js. Just wondering if you can execute this in your browser when you open `https://myhost/wgdashboard/#/signin` please?
```javascript
console.log(`${window.location.protocol}//${window.location.host}${window.location.pathname}`)
```

**Comment by shuricksumy** [comment]
> Hmmmm this is weird. With `v4`, every front-end activity is done on front-end with Vue.js. Just wondering if you can execute this in your browser when you open `https://myhost/wgdashboard/#/signin` please?
> 
> ```js
> console.log(`${window.location.protocol}//${window.location.host}${window.location.pathname}`)
> ```

it returns login form
I did even in postman
image

**Comment by donaldzou** [comment]
What did this returned from your browser when you execute in the console?

```javascript
console.log(`${window.location.protocol}//${window.location.host}${window.location.pathname}`)
```

**Comment by shuricksumy** [comment]
> What did this returned from your browser when you execute in the console?
> 
> ```js
> console.log(`${window.location.protocol}//${window.location.host}${window.location.pathname}`)
> ```
> 
> also did u `git fetch` the latest commit?

I've fetch the latest code

image

**Comment by shuricksumy** [comment]
this is JS code from browser
image

**Comment by donaldzou** [comment]
This is weird.... even your browser is returning `https` from the console.. but somehow the js is not using the browser's protocol.. I just pushed another changes to the branch and it will print out the url front-end is fetching. Could you please let me know what did it print out please?

Screenshot 2024-08-14 at 12 31 58 PM

**Comment by shuricksumy** [comment]
@donaldzou 
Updated but no successes and it looks really weird
image

**Comment by donaldzou** [comment]
Do you see any redirection in your Network tab from Chrome's dev tool?

**Comment by shuricksumy** [comment]
yes, it's blocked

image

**Comment by shuricksumy** [comment]
image

**Comment by donaldzou** [comment]
Ohhhh.. I think the frontend code is correct but somehow the reverse proxy redirect https back to http

> image

**Comment by shuricksumy** [comment]
ok, I will play a bit with traefik rules
I use ordinary config - maybe need to add something

So I will let you know
Thanks for helping

**Comment by donaldzou** [comment]
No problem. Always happy to help 😁

**Comment by shuricksumy** [comment]
@donaldzou 
I found the issue

it's double // in API calls - it produce redirection on server side

I've changed logic to
${window.location.protocol}//${window.location.host}${window.location.pathname.replace(/\/+$/, '')}

and it works
need to delete trailing / in window.location.pathname

**Comment by donaldzou** [comment]
ahah mystery solved! Will update the branch in a sec.

**Comment by shuricksumy** [comment]
@donaldzou 
It's not a critical, just to nice to have - is it possible folder /static also use after the url_prefix ?

It's quite easy to add this in redirection rules but still it needs 2 routes in redirection but maybe one is better ))

**Comment by donaldzou** [comment]
Just updated the branch, let me know if it works :)

**Comment by donaldzou** [comment]
> @donaldzou It's not a critical, just to nice to have - is it possible folder /static also use after the url_prefix ?
> 
> It's quite easy to add this in redirection rules but still it needs 2 routes in redirection but maybe one is better ))
> 
> it actually used for loading web application
> 
> image

I think this could be done ;)

**Comment by shuricksumy** [comment]
@donaldzou 

So help a lot for what you are doing and this project.
I will close this pull request
I have docker builder project for your app -> please fill free to reuse any ready idea [Docker builder](https://github.com/shuricksumy/docker-wgdashboard)

**Comment by shuricksumy** [comment]
closed

**Comment by donaldzou** [comment]
> @donaldzou
> 
> So thanks a lot for what you are doing and this project. I will close this pull request I have docker builder project for your app -> please fill free to reuse any ready idea [Docker builder](https://github.com/shuricksumy/docker-wgdashboard)

No problem! Honestly I think I will just link your repo when I release v4 since I know nothing on Docker so I'll leave it to experts like u ;)

**Pull request closed without merging**
