### PR TITLE
add spanish language

### PR DESCRIPTION
**Pull request by jpizquierdo**

### CODE REVIEW

**Comment by jpizquierdo** [comment]
ohhh i did not see this PR opened! sorry
https://github.com/donaldzou/WGDashboard/pull/423

**Comment by donaldzou** [comment]
Hi!!! No worries and thank you for your work! If you don't mind, can I merge part of your translation to #423 as that one is not completely translated?

**Comment by jpizquierdo** [comment]
@donaldzou yeah sure, feel free, I am glad to be helpful

**Comment by jpizquierdo** [comment]
@donaldzou  btw, If I am able to make a second PR after #423  approval I can add the new words :)

**Comment by donaldzou** [comment]
Screenshot 2024-11-14 at 12 59 54 AM

Everything looks good!

**Comment by donaldzou** [comment]
@jpizquierdo do you mind changing this PR to merge into `main` instead of `v4.1-dev` plz?

**Review by DaanSelen — APPROVED** [review]

**Comment by DaanSelen** [comment]
Looks good to me

**Pull request merged**
