### PR TITLE
Added Gunicorn

### PR DESCRIPTION
**Pull request by pgalonza**
Added Gunicorn for production mode.
I have made minimal changes for add this web-server.
Fixed, exclude grep command from aux result.
Added Let's Encrypt via certbot

Need SERVERURL, EMAIL, CONFIGURATION_PATH, SSL ENV variables

### CODE REVIEW

**Comment by donaldzou** [comment]
Hi, could you please kindly explain what does Gunicorn do? Because I'm not familiar with it. Thank you!

**Comment by ikidd** [comment]
https://vsupalov.com/what-is-gunicorn/

Application server running on the webserver to mediate Python callback requests from what I can gather.

**Comment by donaldzou** [comment]
Hi @ikidd, thank you for providing this, it is actually a good idea, if I understand it correctly, it is kinda like a apache server that wrapped a flask application?

**Comment by pgalonza** [comment]
> Hi @ikidd, thank you for providing this, it is actually a good idea, if I understand it correctly, it is kinda like a apache server that wrapped a flask application?

https://flask.palletsprojects.com/en/2.0.x/deploying/ 
If i understand, web server in flask better for developing and testing.
Using separate server better for security and can using https and i added certbot for Let's Encrypt

**Review by donaldzou — APPROVED** [review]

**Comment by donaldzou** [comment]
Hi! I've been looking into the code for integrating Gunicorn, is it possible that you could create a PR that only contains changes for Gunicorn? I've noticed there are some other changes. Thanks a lot!

**Comment by pgalonza** [comment]
> Hi! I've been looking into the code for integrating Gunicorn, is it possible that you could create a PR that only contains changes for Gunicorn? I've noticed there are some other changes. Thanks a lot!

Sorry, i will be more attentive.

**Comment by donaldzou** [comment]
> > Hi! I've been looking into the code for integrating Gunicorn, is it possible that you could create a PR that only contains changes for Gunicorn? I've noticed there are some other changes. Thanks a lot!
> 
> Sorry, i will be more attentive.

No need to say sorry and I love what you did to helping this project!!

**Comment by donaldzou** [comment]
Hi! I clone a copy of your branch, how should I start the dashboard with gunicorn?

**Comment by pgalonza** [comment]
```
export ENVIRONMENT = production
export SSL = true
cd /app/wgdashboard/src/ && ./wgd.sh start
```

**Comment by donaldzou** [comment]
Hi! I've noticed that the speed to load with Gunicorn is much slower compared to run directly from Flask, is there a reason why?

**Comment by pgalonza** [comment]
> Hi! I've noticed that the speed to load with Gunicorn is much slower compared to run directly from Flask, is there a reason why?

OK, I testing it.

**Comment by donaldzou** [comment]
I think I know why, I just removed locking for every request, can you try to merge main to your branch?

**Comment by donaldzou** [comment]
Yes, it is working perfectly now!!

**Comment by donaldzou** [comment]
Hi! I've successfully merging your branch into my production branch #126 ! But I've noticed that if I do `./wgd.sh start` running it with Gunicorn, it seems not be able to read the global variables, I'm still looking into it.

**Comment by donaldzou** [comment]
Everything is sorted out! I will move any further conversation to #126. Thank you so much for your hard-work!!

**Comment by mar-maradnus** [comment]
Hi, I'm running 3.0.6. I didn't see any option to provide the SSL variables for LetsEncrypt. What am I doing wrong?

**Pull request closed without merging**
