### PR TITLE
Workflow change

### PR DESCRIPTION
**Pull request by DaanSelen**
This changes the Docker image building process from every night to whenever a commit is issued to the main branch. Ensuring the container is not unnecessarily built.

ANALYZING will stay every 24HRs because a CVE can pop-up every day.

### CODE REVIEW

**Comment by DaanSelen** [comment]
I screwed this PR.

** FIRST REVIEW https://github.com/donaldzou/WGDashboard/pull/437 **

**Comment by donaldzou** [comment]
Hi Daan, do you mean the previous PR have incorrect build setup for Docker?

**Comment by DaanSelen** [comment]
No, its the same as the previously mentioned PR, but I accidentally submitted the changes twice.
https://github.com/donaldzou/WGDashboard/pull/447/commits/a93291b38fd1219586c06fafa86ee87916621a4a

This is the only relevant change in this PR

**Comment by donaldzou** [comment]
Ah gotcha. Lmk when is good to merge ;)

**Comment by DaanSelen** [comment]
If you approve the https://github.com/donaldzou/WGDashboard/pull/437 (feel free to merge at your own will).

Then you can look at this which is basically just a schedule change.

**Review by donaldzou — APPROVED** [review]

**Comment by DaanSelen** [comment]
Thanks!

**Pull request merged**
