### PR TITLE
Added Dutch language.

### PR DESCRIPTION
**Pull request by DaanSelen**
Also:

- Alphabetically ordered language list in `active_languages.json`
- Added Dutch language `nl-nl`
- Removed old Docker file (the one in main branch works better)
- Removed Docker image enable (function), WGDashboard can do this now.

### CODE REVIEW

**Comment by DaanSelen** [comment]
Also: this error pops up:
```
[WGDashboard] Starting WGDashboard with Gunicorn in the background.
/opt/wireguarddashboard/src/dashboard.py:1032: SyntaxWarning: invalid escape sequence '\.'
  if _regexMatch(f"^({self.Name})_(.*)\.(conf)$", f):
/opt/wireguarddashboard/src/dashboard.py:1033: SyntaxWarning: invalid escape sequence '\.'
  s = re.search(f"^({self.Name})_(.*)\.(conf)$", f)
/opt/wireguarddashboard/src/dashboard.py:1879: SyntaxWarning: invalid escape sequence '\.'
  if _regexMatch(f"^(.*)_(.*)\.(conf)$", f):
/opt/wireguarddashboard/src/dashboard.py:1880: SyntaxWarning: invalid escape sequence '\.'
  s = re.search(f"^(.*)_(.*)\.(conf)$", f)
```

**Comment by donaldzou** [comment]
Hi Daan, should we let Github handle the merge on docker files?

**Comment by DaanSelen** [comment]
> Hi Daan, should we let Github handle the merge on docker files?

NOOOOO. Well... not without checking, the v4.1-dev branch has the Docker files from before my latest big update... so the best would be to forward the docker files from main and let this PR just be the Dutch language.

**Review by donaldzou — APPROVED** [review]

**Comment by donaldzou** [comment]
Just checked this PR, the docker files should match. Will merge now :)

**Pull request merged**
