### PR TITLE
accept Y and y when asking for are you sure

### PR DESCRIPTION
**Pull request by grufocom**
Used a regex to check for Y or y
Added a ">" to the prompt for user input

### CODE REVIEW

**Comment by DaanSelen** [comment]
I have looked at the change and its compatible. It should still work. Can you verify @grufocom

**Comment by grufocom** [comment]
Hi DaanSelen,

the 4.0 version has an similar aaproach:

Line 449:
> if [ "$up" = "Y" ] || [ "$up" = "y" ]; then

So my commit is not needed to accept y/Y at the prompt. :-)

Regards
Manfred

**Comment by DaanSelen** [comment]
Would your method be better? I know that in principle that it both works, but I am willing to hear your feedback.

**Comment by grufocom** [comment]
it's a matter of taste, both do the same thing - probably the separation into two statements is easier to understand than the one with the regex. :-)

**Comment by DaanSelen** [comment]
Anyway thanks for helping! If you have more suggestions or better ways to do it, let us know! Directly through the Discord or through GitHub!

**Pull request closed without merging**
