### PR TITLE
fixes dependencies not installed

### PR DESCRIPTION
**Pull request by littleblack111**

### CODE REVIEW

**Comment by DaanSelen** [comment]
@littleblack111 does this not get done in line 250?

**Comment by littleblack111** [comment]
@DaanSelen https://github.com/donaldzou/WGDashboard/pull/339/files#diff-0962265adcfbe5f2c55b13d4f96a1b19df395f026a00868df558cb3bf0c54de8R250 just installs python if not installed. and there is installPythonVenv function but it just installs the venv without any dependencies specified in requirements.txt

**Comment by DaanSelen** [comment]
Hi @littleblack111 what about lines 250 to 260 in the current wgd.sh:
```
 _check_and_set_venv
    printf "[WGDashboard] Upgrading Python Package Manage (PIP)\n"
	{ date; python3 -m ensurepip --upgrade; printf "\n\n"; } >> ./log/install.txt
    { date; python3 -m pip install --upgrade pip; printf "\n\n"; } >> ./log/install.txt
    printf "[WGDashboard] Installing latest Python dependencies\n"
    { date; python3 -m pip install -r requirements.txt ; printf "\n\n"; } >> ./log/install.txt
    printf "[WGDashboard] WGDashboard installed successfully!\n"
    printf "[WGDashboard] Enter ./wgd.sh start to start the dashboard\n"
```
` { date; python3 -m pip install -r requirements.txt ; printf "\n\n"; } >> ./log/install.txt` This line specifically.

**Comment by littleblack111** [comment]
thats very weird. I see thats pretty weird since when i first installed this(just pasting the install commands from the README) it didn't have any installed and wgd.sh start just keep complaining about uni sth command not found(which after i manually install it via venv's python -m pip install. then started complaining other modules... thats Y i thought it wasn't installed. unsure if thats just a issue with me or something. So this PR prob wont fix it since that isn't working either so I'll close it

**Comment by DaanSelen** [comment]
> thats very weird. I see thats pretty weird since when i first installed this(just pasting the install commands from the README) it didn't have any installed and wgd.sh start just keep complaining about uni sth command not found(which after i manually install it via venv's python -m pip install. then started complaining other modules... thats Y i thought it wasn't installed. unsure if thats just a issue with me or something. So this PR prob wont fix it since that isn't working either so I'll close it

Thanks for the PR anyway, and if you have some issues, currently, submit an issue and I'll help you!

**Comment by littleblack111** [comment]
ty! But it's all fixed. as i said. i manually installed the requirements.txt on the venv python. so it's all fine now! ty for the help anyways

**Pull request closed without merging**
