### PR TITLE
Fixed #377

### LINKED ISSUE #377: Enable/disable peers
Hello!
Have some issues whis enabled peers.

After testing buttons and use "disable peer", can't enable peers back. 
Deleting disabled peers is also unavailable.

### PR DESCRIPTION
**Pull request by donaldzou**
- Fixed Preshared Key is not added when adding peers
- Fixed Preshared Key Switch UI under bulk add

### CODE REVIEW

**Comment by DaanSelen** [comment]
Everything looks good. But I have to verify the bug. Will ask people in the issue.

**Review by DaanSelen — APPROVED** [review]
Did the code not have checking for the PSK existence before? Anyway, good to have it now.

**Comment by donaldzou** [comment]
> Did the code not have checking for the PSK existence before? Anyway, good to have it now.

I think a Donald in some other parallel universe must implemented that lol.. I do remember fixing that issue but I can't find the commit :(

**Comment by DaanSelen** [comment]
By the way Donald, lets propose Enhancements get merged into 4.2-dev and bugfixes (like this one) get merged into main.

Agree?

**Comment by donaldzou** [comment]
I'm thinking to merge the language template into `main` too.. so contributors can better create locale file ;)

**Pull request merged**
