### PR TITLE
Modified GitHub workflows

### PR DESCRIPTION
**Pull request by DaanSelen**
Added Docker building and analyzing.

For this to work you NEED to add Github secrets and modify the image names so it reflects is well.

Please contact for more info.

### CODE REVIEW

**Comment by donaldzou** [comment]
Hi Daan, sorry for the late reply as I'm traveling lately. Just wondering for this change, if I understand correctly, it will automatically build and push to Docker Hub? If that so, what would need from my side?

Thanks again on the hard work!

**Comment by DaanSelen** [comment]
Hi Donald,

This has 3 workflows:
- Docker builder and push to Docker Hub
- Docker analyzer which can detect any critical vulnerabilities
- CodeQL code scanning

What I need for the docker heb push are GitHub secrets. You can create these here on the website. Under Repo -> Environment secrets. These must be the docker hub name and pass.

CodeQL I updated the versions because the current ones are deprecated (v1).

**Comment by donaldzou** [comment]
Hi Daan, both secrets are set. Let me know if you think is ready to merge and we can try it out.

**Comment by DaanSelen** [comment]
Yes just let me know which account you want to push it to, like what is the name? Mine would be dselen. But your secrets belong to something like Dzou?

**Comment by donaldzou** [comment]
Yes, my account should be `donaldzou`

**Comment by DaanSelen** [comment]
Hi @donaldzou , then it should be done now. Please verify if you agree. And if the DOCKER_HUB_USERNAME and DOCKER_HUB_PASSWORD are inside the repo.

You can verify inside another branch if you'd like. Create like workflow test, before merging into main.

**Comment by DaanSelen** [comment]
@donaldzou merge at will, it merges into another branch

**Comment by DaanSelen** [comment]
@donaldzou please look into the branch 4.1-dev-workflows (or similar) and if you agree, you can merge it into main.

**Comment by donaldzou** [comment]
It looks good, will merge now and fingers crossed lol

**Comment by donaldzou** [comment]
Everything works! thank u!

btw, how do i set an overview on the docker hub page? is there a `readme.md` i can add?

**Comment by DaanSelen** [comment]
> Everything works! thank u!
> 
> btw, how do i set an overview on the docker hub page? is there a `readme.md` i can add?

Perhaps the README.md in the docker folder? With some modifications. I'll look into that, but I still need to do the language I promised.

**Pull request merged**
