### PR TITLE
Second try. Merged Docker update.

### PR DESCRIPTION
**Pull request by DaanSelen**

### CODE REVIEW

**Comment by donaldzou** [comment]
Yeye, will merge now

**Comment by DaanSelen** [comment]
Let's move slowly :) and carefully.

**Review by donaldzou — APPROVED** [review]

**Comment by donaldzou** [comment]
GitHub mentioned it can merge automatically so I just merged your previous PR lol

**Comment by donaldzou** [comment]
Just resolved the conflicts on `Dockerfile`, @DaanSelen could u check if is good?

**Comment by DaanSelen** [comment]
@donaldzou Verify if nothing got lost or anything?

And if you'd like you can run it in docker with
`docker build . -t <image-name>` and then `docker run -d <image-name>`

**Pull request merged**
